# application-rabbitmq.yml - 공통 RabbitMQ 설정
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  queue:
    gps: gps-queue
    onoff: on-off-queue
    web: web-queue
    dlq: dead-letter-queue
